#!/usr/bin/env node
// SPDX-License-Identifier: BUSL-1.1
//
// Fetches the live `tools/list` from the hosted Blackveil DNS Worker and
// regenerates the proxy's tool-catalog surfaces so they can never drift from
// what the backend actually serves:
//
//   - src/fallback-tools.ts   (runtime fallback used when upstream is down)
//   - manifest.json `tools[]`  (Claude Desktop / store directory metadata)
//   - manifest.json `description` + README tool count
//
// Run at pack time via `npm run mcpb:pack`. Network-gated: if the upstream is
// unreachable it leaves existing files untouched and exits non-zero unless
// --allow-offline is passed.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { request as httpsRequest } from 'node:https';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MCP_URL = 'https://dns-mcp.blackveilsecurity.com/mcp';
const ALLOW_OFFLINE = process.argv.includes('--allow-offline');

function post(headers, body) {
	return new Promise((resolve, reject) => {
		const req = httpsRequest(MCP_URL, { method: 'POST', headers, timeout: 30_000 }, (res) => {
			let data = '';
			res.setEncoding('utf8');
			res.on('data', (c) => (data += c));
			res.on('end', () => resolve({ headers: res.headers, body: data }));
		});
		req.on('timeout', () => { req.destroy(); reject(new Error('timeout')); });
		req.on('error', reject);
		req.write(body);
		req.end();
	});
}

async function fetchTools() {
	const baseHeaders = { 'Content-Type': 'application/json', Accept: 'application/json', 'User-Agent': 'bv-claude-dns-sync/1' };
	const init = await post(baseHeaders, JSON.stringify({
		jsonrpc: '2.0', id: 1, method: 'initialize',
		params: { protocolVersion: '2025-03-26', capabilities: {}, clientInfo: { name: 'sync', version: '1' } },
	}));
	const sid = init.headers['mcp-session-id'];
	const sessHeaders = { ...baseHeaders };
	if (typeof sid === 'string') sessHeaders['Mcp-Session-Id'] = sid;
	await post(sessHeaders, JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }));
	const list = await post(sessHeaders, JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} }));
	const parsed = JSON.parse(list.body);
	if (parsed.error || !parsed.result?.tools?.length) throw new Error('empty tools/list');
	return parsed.result.tools;
}

function writeFallback(tools) {
	const slim = tools.map((t) => ({
		name: t.name,
		description: t.description ?? '',
		inputSchema: t.inputSchema ?? { type: 'object', properties: {} },
	}));
	const banner = `// SPDX-License-Identifier: BUSL-1.1
//
// AUTO-GENERATED by scripts/sync-tools.mjs from the live ${MCP_URL} tools/list.
// DO NOT EDIT BY HAND. Used only as a fallback when the upstream is unreachable
// at startup; the proxy fetches the live catalog at runtime when it can.
//
// Generated: ${new Date().toISOString()}

export interface FallbackTool {
\tname: string;
\tdescription: string;
\tinputSchema: { type?: string; properties?: Record<string, unknown>; required?: string[]; [k: string]: unknown };
}

export const FALLBACK_TOOLS: FallbackTool[] = ${JSON.stringify(slim, null, '\t')};
`;
	writeFileSync(join(ROOT, 'src/fallback-tools.ts'), banner);
}

function writeManifest(tools) {
	const path = join(ROOT, 'manifest.json');
	const manifest = JSON.parse(readFileSync(path, 'utf-8'));
	manifest.tools = tools.map((t) => ({ name: t.name, description: t.description ?? '' }));
	// Update the "N tools" count in the description string.
	manifest.description = manifest.description.replace(/\b\d+ tools\b/, `${tools.length} tools`);
	writeFileSync(path, JSON.stringify(manifest, null, '\t') + '\n');
}

function updateCountStrings(tools) {
	const n = tools.length;
	// README: "brings 51 DNS and email security tools" → current count
	const readmePath = join(ROOT, 'README.md');
	let readme = readFileSync(readmePath, 'utf-8');
	readme = readme.replace(/brings \d+ DNS and email security tools/, `brings ${n} DNS and email security tools`);
	writeFileSync(readmePath, readme);
}

(async () => {
	let tools;
	try {
		tools = await fetchTools();
	} catch (err) {
		console.error(`[sync-tools] Could not fetch live catalog: ${err.message}`);
		if (ALLOW_OFFLINE) {
			console.error('[sync-tools] --allow-offline set; leaving generated files untouched.');
			process.exit(0);
		}
		process.exit(1);
	}
	tools.sort((a, b) => a.name.localeCompare(b.name));
	writeFallback(tools);
	writeManifest(tools);
	updateCountStrings(tools);
	console.error(`[sync-tools] Synced ${tools.length} tools → src/fallback-tools.ts, manifest.json, README.md`);
})();
