// SPDX-License-Identifier: BUSL-1.1
//
// AUTO-GENERATED by scripts/sync-tools.mjs from the live https://dns-mcp.blackveilsecurity.com/mcp tools/list.
// DO NOT EDIT BY HAND. Used only as a fallback when the upstream is unreachable
// at startup; the proxy fetches the live catalog at runtime when it can.
//
// Generated: 2026-06-24T10:19:24.248Z

export interface FallbackTool {
	name: string;
	description: string;
	inputSchema: { type?: string; properties?: Record<string, unknown>; required?: string[]; [k: string]: unknown };
}

export const FALLBACK_TOOLS: FallbackTool[] = [
	{
		"name": "analyze_drift",
		"description": "Measure whether a domain's DNS security posture improved or regressed by comparing the current state against a prior scan snapshot. Returns a drift classification (improving/stable/regressing/mixed), score delta, and lists of improvements and regressions. Use to answer \"did our security score improve or regress since last time?\" — distinct from compare_baseline which checks compliance against a fixed policy (not improvement over time).",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to analyze drift for"
				},
				"baseline": {
					"type": "string",
					"minLength": 1,
					"maxLength": 50000,
					"description": "Prior scan reference for drift-over-time analysis: a previous ScanScore JSON STRING, or the literal \"cached\" to reuse the last cached scan. NOT a policy/requirements object — for compliance enforcement against required controls, use compare_baseline instead."
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain",
				"baseline"
			]
		}
	},
	{
		"name": "assess_coverage",
		"description": "Assess Conditional Access coverage gaps for a Microsoft Entra tenant — identifies users and apps not protected by any enforced policy. Requires m365Proxy service binding; returns { unprovisioned: true } when absent. A `representative: true` field in the response marks sample (non-live) data until live Graph reads land.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"ms_tenant_id": {
					"type": "string",
					"minLength": 1,
					"maxLength": 200,
					"description": "Microsoft Entra tenant ID (GUID or domain)."
				}
			},
			"required": [
				"ms_tenant_id"
			]
		}
	},
	{
		"name": "assess_spoofability",
		"description": "Compute a composite email spoofability risk score (0–100, higher = more spoofable) by combining SPF trust surface, DMARC enforcement, and DKIM coverage. Returns a risk level (minimal→critical), per-control sub-scores, and plain-language summary of how easy it would be to spoof email from the domain. Use when asked how easy it is to spoof email from a domain, or for a composite email spoofing risk score.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "batch_scan",
		"description": "Bulk-scan up to 10 domains in parallel. Runs a full security audit on each domain in the list and returns score, letter grade, and finding counts per domain. Use when you want to audit multiple domains at once or do a bulk scan of several domains simultaneously — distinct from compare_domains which does a side-by-side analysis of 2–5 domains.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domains": {
					"minItems": 1,
					"maxItems": 10,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					},
					"description": "Domains to scan (max 10 per request)"
				},
				"force_refresh": {
					"description": "Bypass cache and run fresh scans.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domains"
			]
		}
	},
	{
		"name": "brand_audit_batch_start",
		"description": "Enqueue an async brand audit across up to 50 target domains with optional standard/deep discovery depth, brand aliases, and caller-supplied candidate domains. Returns { auditId, queuedAt, targetCount, etaSeconds } immediately; poll with brand_audit_status and fetch results with brand_audit_get_report once complete. Each target consumes 1 unit of the monthly BRAND_AUDIT_QUOTAS budget.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domains": {
					"minItems": 1,
					"maxItems": 50,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					},
					"description": "Domains to audit (max 50 per batch). Duplicates are merged."
				},
				"format": {
					"description": "Inline output mode. Defaults to \"both\".",
					"anyOf": [
						{
							"type": "string",
							"const": "json"
						},
						{
							"type": "string",
							"const": "markdown"
						},
						{
							"type": "string",
							"const": "both"
						}
					]
				},
				"min_confidence": {
					"description": "Drop candidates whose combined confidence falls below this threshold (0-1, default 0.5).",
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"depth": {
					"description": "Discovery depth. standard is default; deep expands candidate seeding and enrichment fanout.",
					"type": "string",
					"enum": [
						"standard",
						"deep"
					]
				},
				"planner_mode": {
					"description": "Planner mode for staged discovery fanout. observe emits metrics; enforce applies candidate-backed signal caps.",
					"type": "string",
					"enum": [
						"off",
						"observe",
						"enforce"
					]
				},
				"brand_aliases": {
					"description": "Optional public brand aliases to seed, such as product or legal-entity labels.",
					"maxItems": 20,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 2,
						"maxLength": 64
					}
				},
				"candidate_domains": {
					"description": "Optional candidate domains supplied by the caller for corroboration.",
					"maxItems": 250,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					}
				},
				"discovery_mode": {
					"description": "Brand-discovery pipeline mode. classic = legacy sweep; tiered = tenant/graph/evidence wrappers first (BlackVeil-internal).",
					"type": "string",
					"enum": [
						"classic",
						"tiered"
					]
				},
				"ownership_verified": {
					"description": "Caller attests that the target domains are owned or authorized for scanning. Required when discovery_mode is \"tiered\" and the caller is not an enterprise/owner/partner principal.",
					"type": "boolean"
				},
				"view": {
					"description": "Output view mode. 'csc_complement' produces a CSC-tuned payload; requires enterprise tier. Default 'standard'.",
					"type": "string",
					"enum": [
						"standard",
						"csc_complement"
					]
				}
			},
			"required": [
				"domains"
			]
		}
	},
	{
		"name": "brand_audit_get_report",
		"description": "Fetch the result JSON for a completed brand audit. With `target` set, returns the per-target CheckResult; without, returns the audit-level aggregate. Returns notReady when polling an in-flight audit. When a rendered PDF sidecar exists and the R2 binding is configured, metadata includes a signed PDF URL; completed targets without a PDF URL include pdfPending so callers can poll again.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"auditId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 64,
					"description": "Audit ID returned by brand_audit_batch_start."
				},
				"target": {
					"description": "Specific target domain. Omit for audit-level aggregate.",
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				}
			},
			"required": [
				"auditId"
			]
		}
	},
	{
		"name": "brand_audit_single",
		"description": "Run a full brand audit on a single target with optional standard/deep discovery depth, brand aliases, and caller-supplied candidate domains. Discovers brand-related domains, looks up registrar + registrant for each candidate, and classifies each into consolidated, real registrar-sprawl shadowIt, authorized vendor dependency, indeterminate, or impersonation relationships. Gated tier-wide by monthly BRAND_AUDIT_QUOTAS (free/agent=0, developer=50, partner=200, enterprise=500, owner=unlimited).",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Target domain to audit (e.g., apple.com)."
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Inline output mode. Defaults to \"both\".",
					"anyOf": [
						{
							"type": "string",
							"const": "json"
						},
						{
							"type": "string",
							"const": "markdown"
						},
						{
							"type": "string",
							"const": "both"
						}
					]
				},
				"min_confidence": {
					"description": "Drop candidates whose combined confidence falls below this threshold (0-1, default 0.5).",
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"depth": {
					"description": "Discovery depth. standard is default; deep expands candidate seeding and enrichment fanout.",
					"type": "string",
					"enum": [
						"standard",
						"deep"
					]
				},
				"planner_mode": {
					"description": "Planner mode for staged discovery fanout. observe emits metrics; enforce applies candidate-backed signal caps.",
					"type": "string",
					"enum": [
						"off",
						"observe",
						"enforce"
					]
				},
				"brand_aliases": {
					"description": "Optional public brand aliases to seed, such as product or legal-entity labels.",
					"maxItems": 20,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 2,
						"maxLength": 64
					}
				},
				"candidate_domains": {
					"description": "Optional candidate domains supplied by the caller for corroboration.",
					"maxItems": 250,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					}
				},
				"view": {
					"description": "Output view mode. 'csc_complement' produces a CSC-tuned payload; requires enterprise tier. Default 'standard'.",
					"type": "string",
					"enum": [
						"standard",
						"csc_complement"
					]
				},
				"discovery_mode": {
					"description": "Brand-discovery pipeline mode. classic = legacy sweep; tiered = tenant/graph/evidence wrappers first (BlackVeil-internal).",
					"type": "string",
					"enum": [
						"classic",
						"tiered"
					]
				},
				"ownership_verified": {
					"description": "Caller attests that the target domain is owned or authorized for scanning. Required when discovery_mode is \"tiered\" and the caller is not an enterprise/owner/partner principal.",
					"type": "boolean"
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "brand_audit_status",
		"description": "Poll the status of an enqueued brand audit. Returns audit-level status (queued | running | completed | failed), progress 'N/M', and per-target statuses. Owner-scoped — auditIds owned by other principals surface as notFound.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"auditId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 64,
					"description": "Audit ID returned by brand_audit_batch_start."
				}
			},
			"required": [
				"auditId"
			]
		}
	},
	{
		"name": "check_agent_discovery",
		"description": "Assess the security posture of IETF BANDAID agent-discovery records (draft-mozleywilliams-dnsop-dnsaid). Detects SVCB agent records under _agents/_index._{protocol}._agents, reports whether the discovery zone is DNSSEC-anchored (unsigned = spoofable agent endpoints), evaluates DANE/TLSA binding trust (RFC 6698 §10.1), and checks capability-document integrity (cap / cap-sha256). Read-only; uses Private-Use SVCB param code points pending IANA assignment.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check for published agent-discovery records (e.g., example.com)."
				},
				"protocol": {
					"description": "Scope discovery to a single agent protocol index (_index._{protocol}._agents). Omit to sweep the zone.",
					"type": "string",
					"enum": [
						"a2a",
						"mcp",
						"https"
					]
				},
				"name": {
					"description": "Resolve a single named agent ({name}.{domain}) instead of enumerating the zone.",
					"type": "string",
					"minLength": 1,
					"maxLength": 63
				},
				"verify_cap": {
					"description": "Fetch each declared capability document (cap=) over HTTPS via safeFetch and verify it against the cap-sha256 integrity pin. Default false (declaration/existence check only).",
					"type": "boolean"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_authoritative_dns_infra",
		"description": "Check authoritative DNS infrastructure posture for a hostname. Uses BV_INFRA_PROBE when available for raw DNS, routing, RPKI, and vantage-point evidence.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_bimi",
		"description": "Check the BIMI brand-logo record at default._bimi.<domain>. Validates the logo URL (l=) and VMC certificate evidence (a=), and verifies the DMARC enforcement prerequisite (p=quarantine/reject) that mail clients require before displaying a BIMI logo. Returns findings for a missing/malformed record or unmet prerequisites. Use to assess brand-indicator readiness in inboxes. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_caa",
		"description": "Look up CAA records for a domain. Shows which Certificate Authorities are authorized to issue certificates. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dane",
		"description": "Check DANE/TLSA certificate pinning for SMTP at port 25. Resolves the domain's MX hosts and looks up TLSA records at _25._tcp.<mx-host>, verifying whether SMTP mail-server certificates are bound in DNS (DNSSEC-backed protection against CA misissuance and MITM on inbound mail). Use when asked if SMTP connections are protected by DANE/TLSA pinning. For HTTPS DANE at port 443, use check_dane_https instead. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dane_https",
		"description": "Verify DANE certificate pinning for HTTPS connections. Looks up TLSA records at _443._tcp.{domain} (port 443) to confirm the web certificate is pinned in DNS. Distinct from check_dane which covers SMTP at port 25. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dbl",
		"description": "Check domain reputation against DNS-based Domain Block Lists (Spamhaus DBL, URIBL, SURBL). Returns listing status with decoded return codes.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dkim",
		"description": "Look up DKIM records for a domain. Probes common selectors, validates the signing algorithm used for outgoing email (RSA-1024/2048, Ed25519), and reports key strength. Use to verify that outbound email signatures are cryptographically sound. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"selector": {
					"description": "DKIM selector. Omit to probe common ones.",
					"type": "string",
					"maxLength": 63,
					"pattern": "^[a-z0-9]([a-z0-9-]*[a-z0-9])?$"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dmarc",
		"description": "Look up and validate the DMARC record for a domain. Shows the enforcement level (none/quarantine/reject), alignment mode (strict/relaxed), and aggregate/forensic reporting destinations. Use to determine a domain's DMARC enforcement level, whether it sends aggregate reports, or if it is protected against email impersonation — distinct from check_shadow_domains (which checks TLD variants) and assess_spoofability (composite score). Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dnskey_strength",
		"description": "Audit the cryptographic strength of DNSKEY signing algorithms used for DNSSEC. Reports which algorithm is used for DNSSEC signing keys (RSA/SHA-1, RSA/SHA-256, ECDSA P-256, Ed25519, etc.), flags deprecated algorithms (RSA/SHA-1, DSA), independent of whether the DNSSEC chain validates. Use when asked what algorithm is used for DNSSEC signing keys, or if deprecated DNSKEY algorithms are in use. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dnssec",
		"description": "Check DNSSEC status for a domain. Verifies whether DNS is tamper-proof and protected against cache poisoning and DNS spoofing attacks by validating DNSKEY and DS records. Reports whether DNSSEC is enabled and validating. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_dnssec_chain",
		"description": "Walk the full DNSSEC chain of trust from the DNS root down to the target domain, tracing DS/DNSKEY records and algorithm usage at each zone level. Use when asked to trace the chain of trust from the DNS root, or to see the full DNSSEC delegation path step by step.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_fast_flux",
		"description": "Detect fast-flux DNS behavior: performs multiple rounds of A/AAAA queries and checks whether IP addresses are rotating rapidly on each DNS query (a sign of botnet or malicious infrastructure). Compares IP answer sets and TTLs across rounds to identify rapidly rotating infrastructure used to hide malicious activity.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"rounds": {
					"description": "Number of query rounds (3-5, default 3).",
					"type": "integer",
					"minimum": 3,
					"maximum": 5
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_http_security",
		"description": "Audit a domain's browser-facing HTTP security headers over HTTPS. Inspects Content-Security-Policy (flagging unsafe-inline/unsafe-eval/wildcards), X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, and the cross-origin isolation headers (COOP/COEP/CORP), and detects CDN/WAF interception. Returns per-header findings for missing or weak protections against XSS, clickjacking, and cross-origin attacks. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_lookalikes",
		"description": "Detect active typosquat and lookalike/homoglyph domains that impersonate your brand and could be used in phishing. Identifies character-substitution and visual-confusion domains registered by attackers. Distinct from check_shadow_domains (TLD variants with auth gaps) and discover_brand_domains (legitimate brand portfolio).",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_mta_sts",
		"description": "Check whether a domain enforces SMTP TLS for inbound mail via MTA-STS, protecting against downgrade attacks. Queries _mta-sts.<domain> and fetches the policy file, reports mode (enforce/testing/none) and MX coverage. Use to verify whether inbound SMTP is protected against TLS downgrade or MITM — distinct from check_dane which uses TLSA pinning. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_mx",
		"description": "Look up MX records for a domain. Identifies which mail servers receive inbound email for the domain and which email hosting provider is used (Google Workspace, Microsoft 365, Proofpoint, etc.). Use when asked which email provider hosts inbound mail for a domain, or to see MX record configuration. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_mx_reputation",
		"description": "Check whether the mail server (MX) IP addresses are listed on spam blocklists (Spamhaus, Barracuda, SORBS, and other RBLs). Also verifies reverse DNS for MX hosts. Use when you want to know if your mail server IP is blacklisted, or if your MX is on any blocklist — distinct from check_rbl which checks a specific IP directly.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_ns",
		"description": "Look up NS (nameserver) records for a domain. Identifies the DNS nameserver provider (Cloudflare, Route53, NS1, etc.) and shows delegation and redundancy. Use to find out which authoritative nameserver or DNS hosting service is used for a domain. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_nsec_walkability",
		"description": "Assess zone walkability risk by analyzing NSEC3PARAM configuration. Detects plain NSEC zones, weak NSEC3 parameters, and opt-out flags.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_ptr",
		"description": "Verify forward-confirmed reverse DNS (PTR/FCrDNS) for mail servers. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_rbl",
		"description": "Check MX server IP reputation against 7 DNS-based Real-time Blocklists (SpamCop, UCEProtect, Mailspike, Barracuda, PSBL, SORBS). Resolves MX hosts to IPs first.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_realtime_threat_feed",
		"description": "Check a domain against BlackVeil real-time threat intelligence (curated intel-gateway feed). Distinct from DNSBL checks. Operator-deploy only; degrades to info when unprovisioned.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_resolver_consistency",
		"description": "Check DNS consistency across 4 public resolvers.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"record_type": {
					"description": "Record type. Omit for A/AAAA/MX/TXT/NS.",
					"type": "string",
					"enum": [
						"A",
						"AAAA",
						"MX",
						"TXT",
						"NS",
						"CNAME",
						"SOA",
						"CAA"
					]
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_root_server_set",
		"description": "Check the DNS root server set against official root hints, root glue, delegation, serial, and DNSKEY cross-root evidence.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			}
		}
	},
	{
		"name": "check_shadow_domains",
		"description": "Find alternate TLD variants of a domain (e.g. example.net, example.co) that have weak or missing email authentication and could be used to spoof email. Use when asked about TLD variants with email auth gaps — distinct from check_lookalikes which detects typosquat/homoglyph impersonation domains.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_spf",
		"description": "Look up and validate the SPF record for a domain. Lists all IP addresses and third-party senders authorised to send email on behalf of the domain, flags syntax errors, and shows the trust surface (which mail servers are whitelisted). Use when you need to know who is permitted to send email as a domain. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_srv",
		"description": "Map a domain's DNS-visible service footprint by probing ~16 common SRV record prefixes (email, calendar, messaging, web, directory) in parallel. Returns discovered services and flags insecure service advertisements — e.g. plaintext IMAP/POP3 without an encrypted variant. Use when asked to map DNS-visible services or flag insecure service advertisements.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_ssl",
		"description": "Check the SSL/TLS certificate for a domain. Shows the issuer (Certificate Authority), expiry date (when the certificate expires), supported protocol versions (TLS 1.2/1.3), and HTTPS configuration. Use to verify certificate validity and who issued it. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_subdomailing",
		"description": "Detect SubdoMailing risk: analyzes the SPF include chain for dangling or hijackable subdomains that could let an attacker send email as the domain. Use when you want to know if an SPF include chain can be hijacked through a dangling domain, or to detect subdomain mailing risk hidden in SPF includes. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_subdomain_takeover",
		"description": "Sweep subdomains for dangling CNAMEs pointing to deprovisioned cloud services that could be claimed by an attacker (subdomain takeover vulnerabilities). Detects 16 provider families (AWS S3/CloudFront, Azure Front Door/CDN/Blob/App Service, GCP Cloud Storage, Heroku, GitHub Pages, Vercel, Firebase, Shopify, etc.). Use when asked if subdomains are pointing to deprovisioned cloud services. Pair with discover_subdomains for full inventory.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)."
				},
				"subdomains": {
					"description": "Optional explicit subdomain list (full FQDNs or short labels). When provided (deduped, capped at 1000), this list is swept instead of the 15-name built-in. Source from Certificate-Transparency enumeration or brand-audit discovery.",
					"maxItems": 1000,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					}
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_svcb_https",
		"description": "Validate HTTPS/SVCB records (RFC 9460) for modern transport capability advertisement. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_tlsrpt",
		"description": "Check whether a domain has SMTP TLS Reporting (TLS-RPT) configured. Queries _smtp._tls.<domain> for the v=TLSRPTv1 record and validates its reporting destination (rua= mailto:/https:), flagging a missing record, duplicate records, or an invalid/absent reporting URI. Complements MTA-STS by giving visibility into TLS delivery failures. Part of the scan_domain audit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_txt_hygiene",
		"description": "Audit TXT records for stale entries and SaaS exposure.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "check_zone_hygiene",
		"description": "Audit DNS zone hygiene: identifies sensitive or forgotten subdomains exposed in DNS, stale SOA records, and zone propagation issues. Use to find any sensitive subdomains that should not be publicly visible, or to audit overall DNS zone cleanliness.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "compare_baseline",
		"description": "Compare a domain's current security configuration against a fixed policy baseline to determine compliance. Use to check whether a domain meets a policy requirement — not for tracking improvement/regression over time (use analyze_drift) and not for comparing multiple domains (use compare_domains).",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to scan and compare."
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				},
				"baseline": {
					"type": "object",
					"properties": {
						"grade": {
							"description": "Min grade (e.g., \"B+\").",
							"type": "string",
							"enum": [
								"A+",
								"A",
								"B+",
								"B",
								"C+",
								"C",
								"D+",
								"D",
								"F"
							]
						},
						"score": {
							"description": "Min score (0-100).",
							"type": "number",
							"minimum": 0,
							"maximum": 100
						},
						"require_dmarc_enforce": {
							"description": "Require DMARC enforce.",
							"type": "boolean"
						},
						"require_spf": {
							"description": "Require SPF.",
							"type": "boolean"
						},
						"require_dkim": {
							"description": "Require DKIM.",
							"type": "boolean"
						},
						"require_dnssec": {
							"description": "Require DNSSEC.",
							"type": "boolean"
						},
						"require_mta_sts": {
							"description": "Require MTA-STS.",
							"type": "boolean"
						},
						"require_caa": {
							"description": "Require CAA.",
							"type": "boolean"
						},
						"max_critical_findings": {
							"description": "Max critical findings (default 0).",
							"type": "integer",
							"minimum": 0,
							"maximum": 9007199254740991
						},
						"max_high_findings": {
							"description": "Max high findings allowed.",
							"type": "integer",
							"minimum": 0,
							"maximum": 9007199254740991
						}
					},
					"additionalProperties": {},
					"description": "Policy/requirements baseline OBJECT for compliance enforcement — \"does this domain meet these required controls?\" (grade/score floors, require_* flags, max_*_findings). NOT a prior scan. For drift-over-time vs a previous ScanScore (or the literal \"cached\"), use analyze_drift instead."
				}
			},
			"required": [
				"domain",
				"baseline"
			]
		}
	},
	{
		"name": "compare_domains",
		"description": "Side-by-side security comparison of 2–5 domains. Shows relative scores, category gaps, and unique weaknesses for each domain. Use when comparing your security posture against a competitor, or doing a head-to-head comparison between multiple domains.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domains": {
					"minItems": 2,
					"maxItems": 5,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					},
					"description": "Domains to compare (2–5 domains)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domains"
			]
		}
	},
	{
		"name": "cymru_asn",
		"description": "Map domain IPs to Autonomous System Numbers via Team Cymru DNS. Returns ASN, prefix, country, registry, and organization for each IP. Flags high-risk hosting ASNs.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "delete_brand_audit_watch",
		"description": "Permanently removes a recurring brand-audit watch by watchId. Owner-scoped — a watchId owned by another principal surfaces as notFound. Returns confirmation of deletion.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"watchId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 64,
					"description": "Watch ID returned by register_brand_audit_watch."
				}
			},
			"required": [
				"watchId"
			]
		}
	},
	{
		"name": "discover_brand_domains",
		"description": "Discover all domains that belong to a brand's portfolio by aggregating certificate, DNS, redirect, and mail-policy signals. Use when asked what domains are part of a brand portfolio, or to find all domains related to a brand. Pass the EXACT seed domain verbatim — do NOT normalize or substitute a canonical domain.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "The exact seed domain to expand, scanned verbatim (e.g., example.com). Do NOT normalize, resolve, or substitute a brand's canonical/main domain — pass the literal domain the user named (e.g. pass `clau.de`, not `anthropic.com`). Use `brand_aliases` for related brand labels."
				},
				"signals": {
					"description": "Signal modules to invoke. Defaults to all 12 discovery/enrichment signals.",
					"minItems": 1,
					"maxItems": 12,
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"san",
							"san_recursive",
							"ns",
							"dmarc_rua",
							"dkim_key_reuse",
							"http_redirect",
							"mx_overlap",
							"txt_verification",
							"mx_platform",
							"spf_include",
							"spf_include_seed",
							"cname_alignment"
						]
					}
				},
				"depth": {
					"description": "Discovery depth. standard is default; deep expands candidate seeding and enrichment fanout.",
					"type": "string",
					"enum": [
						"standard",
						"deep"
					]
				},
				"planner_mode": {
					"description": "Planner mode for staged discovery fanout. observe emits metrics; enforce applies candidate-backed signal caps.",
					"type": "string",
					"enum": [
						"off",
						"observe",
						"enforce"
					]
				},
				"brand_aliases": {
					"description": "Optional public brand aliases to seed, such as product or legal-entity labels.",
					"maxItems": 20,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 2,
						"maxLength": 64
					}
				},
				"candidate_domains": {
					"description": "Optional candidate domains supplied by the caller for corroboration.",
					"maxItems": 250,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					}
				},
				"dkim_selectors": {
					"description": "Optional DKIM selectors to probe. Defaults to a built-in common-selector list.",
					"maxItems": 50,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 63
					}
				},
				"min_confidence": {
					"description": "Drop candidates whose combined confidence falls below this threshold (0-1, default 0.5).",
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"discovery_mode": {
					"default": "classic",
					"description": "Discovery mode. \"classic\" (default, BSL-licensed) runs the public signal-sweep pipeline. \"tiered\" layers Tier 0 (tenant-declared portfolio), Tier 1 (infrastructure-graph), and Tier 2 (declared-evidence) lookups in front of the legacy sweep, falling back to Tier 3 (the existing sweep) only on cache miss / very_stale fingerprint / uncovered caller candidates. Tiered mode requires private BlackVeil service bindings — BSL self-hosts should leave this on \"classic\".",
					"type": "string",
					"enum": [
						"classic",
						"tiered"
					]
				},
				"ownership_verified": {
					"description": "Caller attests that the seed domain is owned or authorized for scanning. Required when discovery_mode is \"tiered\" and the caller is not an enterprise/owner/partner principal. Prevents unauthorized mass reconnaissance via deep tier lookups.",
					"type": "boolean"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain",
				"discovery_mode"
			]
		}
	},
	{
		"name": "discover_brand_domains_findings",
		"description": "Fetch the ranked candidate domains (the discovery CheckResult) for an async run started with discover_brand_domains_start. Returns notReady while the discovery is still in-flight; the discovery result once complete. Owner-scoped.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"operationId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 64,
					"description": "Operation ID returned by discover_brand_domains_start."
				}
			},
			"required": [
				"operationId"
			]
		}
	},
	{
		"name": "discover_brand_domains_start",
		"description": "Start an async brand-domain discovery for the EXACT seed domain provided (the async sibling of discover_brand_domains, which can run ~24s and time out interactive clients). Same args as discover_brand_domains. Returns { auditId, queuedAt, etaSeconds } immediately; poll with discover_brand_domains_status and fetch ranked candidates with discover_brand_domains_findings once complete.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "The exact seed domain to expand, scanned verbatim (e.g., example.com). Do NOT normalize, resolve, or substitute a brand's canonical/main domain — pass the literal domain the user named (e.g. pass `clau.de`, not `anthropic.com`). Use `brand_aliases` for related brand labels."
				},
				"signals": {
					"description": "Signal modules to invoke. Defaults to all 12 discovery/enrichment signals.",
					"minItems": 1,
					"maxItems": 12,
					"type": "array",
					"items": {
						"type": "string",
						"enum": [
							"san",
							"san_recursive",
							"ns",
							"dmarc_rua",
							"dkim_key_reuse",
							"http_redirect",
							"mx_overlap",
							"txt_verification",
							"mx_platform",
							"spf_include",
							"spf_include_seed",
							"cname_alignment"
						]
					}
				},
				"depth": {
					"description": "Discovery depth. standard is default; deep expands candidate seeding and enrichment fanout.",
					"type": "string",
					"enum": [
						"standard",
						"deep"
					]
				},
				"planner_mode": {
					"description": "Planner mode for staged discovery fanout. observe emits metrics; enforce applies candidate-backed signal caps.",
					"type": "string",
					"enum": [
						"off",
						"observe",
						"enforce"
					]
				},
				"brand_aliases": {
					"description": "Optional public brand aliases to seed, such as product or legal-entity labels.",
					"maxItems": 20,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 2,
						"maxLength": 64
					}
				},
				"candidate_domains": {
					"description": "Optional candidate domains supplied by the caller for corroboration.",
					"maxItems": 250,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253
					}
				},
				"dkim_selectors": {
					"description": "Optional DKIM selectors to probe. Defaults to a built-in common-selector list.",
					"maxItems": 50,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 63
					}
				},
				"min_confidence": {
					"description": "Drop candidates whose combined confidence falls below this threshold (0-1, default 0.5).",
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"discovery_mode": {
					"default": "classic",
					"description": "Discovery mode. \"classic\" (default, BSL-licensed) runs the public signal-sweep pipeline. \"tiered\" layers Tier 0 (tenant-declared portfolio), Tier 1 (infrastructure-graph), and Tier 2 (declared-evidence) lookups in front of the legacy sweep, falling back to Tier 3 (the existing sweep) only on cache miss / very_stale fingerprint / uncovered caller candidates. Tiered mode requires private BlackVeil service bindings — BSL self-hosts should leave this on \"classic\".",
					"type": "string",
					"enum": [
						"classic",
						"tiered"
					]
				},
				"ownership_verified": {
					"description": "Caller attests that the seed domain is owned or authorized for scanning. Required when discovery_mode is \"tiered\" and the caller is not an enterprise/owner/partner principal. Prevents unauthorized mass reconnaissance via deep tier lookups.",
					"type": "boolean"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain",
				"discovery_mode"
			]
		}
	},
	{
		"name": "discover_brand_domains_status",
		"description": "Poll the status of an async brand-domain discovery started with discover_brand_domains_start. Returns status (queued | running | completed | failed) and progress. Owner-scoped — operationIds owned by other principals surface as notFound.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"operationId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 64,
					"description": "Operation ID returned by discover_brand_domains_start."
				}
			},
			"required": [
				"operationId"
			]
		}
	},
	{
		"name": "discover_subdomains",
		"description": "Find subdomains of a domain using Certificate Transparency logs. Reveals shadow IT, forgotten services, and unauthorized certificate issuance.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "explain_finding",
		"description": "Explain a finding with impact and remediation.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"checkType": {
					"type": "string",
					"minLength": 1,
					"maxLength": 100,
					"description": "Check type (e.g., 'SPF', 'DMARC')."
				},
				"status": {
					"description": "Finding severity or status.",
					"type": "string",
					"enum": [
						"pass",
						"fail",
						"warning",
						"critical",
						"high",
						"medium",
						"low",
						"info"
					]
				},
				"details": {
					"description": "Additional detail from check result.",
					"type": "string",
					"maxLength": 2000
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"checkType",
				"status"
			]
		}
	},
	{
		"name": "generate",
		"description": "Generate a DNS/email security remediation artifact. Artifact types: spf_record (build a new SPF record), dmarc_record (create a DMARC policy), dkim_config (DKIM key setup), mta_sts_policy (generate an MTA-STS policy file), fix_plan (prioritized remediation plan for all findings), or rollout_plan (phased DMARC enforcement timeline). Use when asked to generate or create a record or policy.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"artifact": {
					"type": "string",
					"enum": [
						"fix_plan",
						"spf_record",
						"dmarc_record",
						"dkim_config",
						"mta_sts_policy",
						"rollout_plan"
					],
					"description": "Which artifact to generate (e.g., \"dmarc_record\", \"fix_plan\")."
				},
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain (e.g., example.com)"
				},
				"include_providers": {
					"description": "spf_record: providers to include (e.g., [\"google\"]).",
					"maxItems": 15,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253,
						"pattern": "^[a-z0-9._-]+$"
					}
				},
				"policy": {
					"description": "dmarc_record: policy (default \"reject\").",
					"type": "string",
					"enum": [
						"none",
						"quarantine",
						"reject"
					]
				},
				"rua_email": {
					"description": "dmarc_record: report email. Default: dmarc-reports@{domain}.",
					"type": "string",
					"maxLength": 254,
					"pattern": "^[^\\s;,@\\x00-\\x1f\\x7f]+@[^\\s;,@\\x00-\\x1f\\x7f]+\\.[^\\s;,@\\x00-\\x1f\\x7f]+$"
				},
				"provider": {
					"description": "dkim_config: provider (e.g., \"google\"). Omit for generic.",
					"type": "string",
					"maxLength": 100
				},
				"mx_hosts": {
					"description": "mta_sts_policy: MX hosts. Omit to detect from DNS.",
					"maxItems": 20,
					"type": "array",
					"items": {
						"type": "string",
						"minLength": 1,
						"maxLength": 253,
						"pattern": "^[^\\s\\x00-\\x1f\\x7f]*$"
					}
				},
				"target_policy": {
					"description": "rollout_plan: target DMARC policy (default: reject).",
					"type": "string",
					"enum": [
						"quarantine",
						"reject"
					]
				},
				"timeline": {
					"description": "rollout_plan: rollout speed (default: standard).",
					"type": "string",
					"enum": [
						"aggressive",
						"standard",
						"conservative"
					]
				},
				"force_refresh": {
					"description": "fix_plan: bypass cache and run a fresh scan.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"artifact",
				"domain"
			]
		}
	},
	{
		"name": "get_benchmark",
		"description": "Get industry benchmark data: shows what percentile a domain's security score ranks at within its sector or country cohort, the mean score, and the most common DNS security failures across the industry. Use when asked how a score compares to the industry average, what percentile a score is in, or what the most common security failures are in an industry or sector.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"profile": {
					"description": "Profile to benchmark (default \"mail_enabled\").",
					"type": "string",
					"enum": [
						"mail_enabled",
						"enterprise_mail",
						"non_mail",
						"web_only",
						"minimal",
						"authoritative_dns_infra"
					]
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			}
		}
	},
	{
		"name": "get_ca_policies",
		"description": "Retrieve Conditional Access policies for a Microsoft Entra tenant. Requires m365Proxy service binding; returns { unprovisioned: true } when absent. A `representative: true` field in the response marks sample (non-live) data until live Graph reads land.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"ms_tenant_id": {
					"type": "string",
					"minLength": 1,
					"maxLength": 200,
					"description": "Microsoft Entra tenant ID (GUID or domain)."
				}
			},
			"required": [
				"ms_tenant_id"
			]
		}
	},
	{
		"name": "get_domain_rank",
		"description": "Rank a domain against its country or global cohort using the GSI benchmark corpus. Accepts a domain score (from scan_domain) and optional country/sector; returns a percentile: \"scores better than X% of peers\". Owner-gate exempt — public cohort data only.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to rank against its cohort (e.g., example.com)"
				},
				"score": {
					"type": "number",
					"minimum": 0,
					"maximum": 100,
					"description": "Domain score (0–100) from scan_domain. Used to compute the cohort percentile."
				},
				"country": {
					"description": "ISO 3166-1 alpha-2 country code to use the country cohort (e.g., \"NZ\"). Omit for global cohort.",
					"type": "string",
					"minLength": 2,
					"maxLength": 2
				},
				"sector": {
					"description": "Sector label (e.g., \"finance\"). Forwarded to the cohort endpoint; sector filtering is planned for a future release.",
					"type": "string",
					"minLength": 1,
					"maxLength": 100
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain",
				"score"
			]
		}
	},
	{
		"name": "get_provider_insights",
		"description": "Get security benchmarks and common configuration issues for a specific email or DNS service-provider cohort (e.g. Google Workspace customers, Microsoft 365 customers). Use when asked how an email service provider compares to competitors on security posture, or to see typical misconfigurations for a named vendor's customers.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"provider": {
					"type": "string",
					"minLength": 1,
					"maxLength": 200,
					"description": "Provider (e.g., \"google workspace\")."
				},
				"profile": {
					"description": "Profile (default \"mail_enabled\").",
					"type": "string",
					"enum": [
						"mail_enabled",
						"enterprise_mail",
						"non_mail",
						"web_only",
						"minimal",
						"authoritative_dns_infra"
					]
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"provider"
			]
		}
	},
	{
		"name": "list_brand_audit_watches",
		"description": "Returns the caller's recurring brand-audit watches: watchId, domain, interval, webhook presence, last-run time, and active state. Owner-scoped. Read-only.",
		"inputSchema": {
			"type": "object",
			"properties": {}
		}
	},
	{
		"name": "map_compliance",
		"description": "Map scan findings to compliance frameworks: NIST 800-177, PCI DSS 4.0, SOC 2, CIS Controls. Shows pass/fail/partial status per control.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "map_supply_chain",
		"description": "Map DNS-visible third-party service dependencies for a domain. Correlates SPF, NS, TXT verifications, SRV services, and CAA records to reveal which third-party vendors can send email as the domain, control DNS, or access integrated services. Use when asked to map third-party or supply-chain dependencies — not for listing who can send email (use check_spf for that).",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "osint_investigate_domain_start",
		"description": "Start an async OSINT investigation for a domain. Operator-deploy only; degrades to info when unprovisioned. Returns an investigationId immediately — poll with osint_investigation_status and retrieve results with osint_investigation_report.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"query": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				}
			},
			"required": [
				"query"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "osint_investigate_email_start",
		"description": "Start an async OSINT investigation for an email address (breach exposure, account correlation). Owner/enterprise tier only — people-centric OSINT is restricted to prevent misuse. Returns an investigationId immediately — poll with osint_investigation_status and retrieve results with osint_investigation_report.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"query": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				}
			},
			"required": [
				"query"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "osint_investigate_infrastructure_start",
		"description": "Start an async deep-infrastructure OSINT investigation for a query (domain, IP, or org). Operator-deploy only; degrades to info when unprovisioned. Returns an investigationId immediately — poll with osint_investigation_status.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"query": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				}
			},
			"required": [
				"query"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "osint_investigate_supply_chain_start",
		"description": "Start an async supply-chain OSINT investigation for a query. Operator-deploy only; degrades to info when unprovisioned. Returns an investigationId immediately — poll with osint_investigation_status.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"query": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				}
			},
			"required": [
				"query"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "osint_investigate_username_start",
		"description": "Start an async OSINT investigation for a username (cross-platform presence, breach correlation). Owner/enterprise tier only — people-centric OSINT is restricted to prevent misuse. Returns an investigationId immediately — poll with osint_investigation_status and retrieve results with osint_investigation_report.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"query": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				}
			},
			"required": [
				"query"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "osint_investigation_report",
		"description": "Retrieve the final report of a completed OSINT investigation by investigationId. Operator-deploy only; degrades to info when unprovisioned or not yet complete.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"investigationId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 128
				}
			},
			"required": [
				"investigationId"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "osint_investigation_status",
		"description": "Poll the status of an OSINT investigation by investigationId. Operator-deploy only; degrades to info when unprovisioned. Returns current status (running | completed | failed) and progress metadata.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"investigationId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 128
				}
			},
			"required": [
				"investigationId"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "query_signins",
		"description": "Query Microsoft Entra sign-in logs for a tenant. Optionally filter by user principal name, failure status, or lookback window. Requires m365Proxy service binding; returns { unprovisioned: true } when absent. A `representative: true` field in the response marks sample (non-live) data until live Graph reads land.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"ms_tenant_id": {
					"type": "string",
					"minLength": 1,
					"maxLength": 200,
					"description": "Microsoft Entra tenant ID (GUID or domain)."
				},
				"user_principal_name": {
					"description": "Filter to a specific user (UPN). Omit for all users.",
					"type": "string",
					"maxLength": 254
				},
				"failures_only": {
					"description": "When true, return only failed sign-ins.",
					"type": "boolean"
				},
				"since_hours": {
					"description": "Lookback window in hours (default: 24, max: 720).",
					"type": "integer",
					"minimum": 1,
					"maximum": 720
				}
			},
			"required": [
				"ms_tenant_id"
			]
		}
	},
	{
		"name": "query_ual",
		"description": "Query the Microsoft 365 Unified Audit Log for a tenant. Optionally filter by operation type, user, or lookback window. Requires m365Proxy service binding; returns { unprovisioned: true } when absent. A `representative: true` field in the response marks sample (non-live) data until live Graph reads land.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"ms_tenant_id": {
					"type": "string",
					"minLength": 1,
					"maxLength": 200,
					"description": "Microsoft Entra tenant ID (GUID or domain)."
				},
				"operation": {
					"description": "Filter to a specific Unified Audit Log operation (e.g., \"MailItemsAccessed\").",
					"type": "string",
					"maxLength": 200
				},
				"user_principal_name": {
					"description": "Filter to a specific user (UPN). Omit for all users.",
					"type": "string",
					"maxLength": 254
				},
				"since_hours": {
					"description": "Lookback window in hours (default: 24, max: 720).",
					"type": "integer",
					"minimum": 1,
					"maximum": 720
				}
			},
			"required": [
				"ms_tenant_id"
			]
		}
	},
	{
		"name": "rdap_lookup",
		"description": "Fetch domain registration data via RDAP (modern WHOIS replacement). Returns the domain registrar (the company the domain was registered with), registrant contact, creation/expiration dates, EPP status codes, and domain age. Use when asked who registered the domain, who the registrar is, or when the registration expires — distinct from check_ns which identifies the DNS nameserver provider.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "register_brand_audit_watch",
		"description": "Creates a recurring brand-audit watch for a domain on a daily/weekly/monthly cadence. Each run enqueues a fresh brand_audit_batch_start and (when a webhook is configured) POSTs a diff webhook on classification drift. Returns the new watchId. Owner-scoped; per-principal cap of 20 active watches.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to watch."
				},
				"interval": {
					"type": "string",
					"enum": [
						"daily",
						"weekly",
						"monthly"
					],
					"description": "Recurrence interval."
				},
				"webhook_url": {
					"description": "Optional webhook URL — POSTed on classification drift. Re-validated for SSRF at both register and delivery time.",
					"type": "string",
					"maxLength": 2048,
					"format": "uri"
				}
			},
			"required": [
				"domain",
				"interval"
			]
		}
	},
	{
		"name": "resolve_spf_chain",
		"description": "Trace the full SPF include chain for a domain. Recursively resolves all includes, shows lookup count, tree depth, and flags circular includes or exceeding the 10-lookup limit.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "scan_buckets_findings",
		"description": "Retrieve findings from a completed cloud-bucket discovery scan. Operator-deploy only; degrades to info when unprovisioned. Optionally scoped to a specific scanId, target, and provider list; omit scanId to retrieve the most recent findings.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"scanId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 128
				},
				"target": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				},
				"providers": {
					"maxItems": 8,
					"type": "array",
					"items": {
						"type": "string",
						"maxLength": 32
					}
				}
			},
			"additionalProperties": false
		}
	},
	{
		"name": "scan_buckets_start",
		"description": "Start an async cloud-bucket discovery scan for a target domain. Operator-deploy only; degrades to info when unprovisioned. Returns a scanId immediately — poll progress with scan_buckets_status and retrieve results with scan_buckets_findings.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"target": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253
				},
				"providers": {
					"maxItems": 8,
					"type": "array",
					"items": {
						"type": "string",
						"maxLength": 32
					}
				}
			},
			"required": [
				"target"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "scan_buckets_status",
		"description": "Poll the status of a cloud-bucket discovery scan by scanId. Operator-deploy only; degrades to info when unprovisioned. Returns scan status (running | completed | failed) and progress metadata.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"scanId": {
					"type": "string",
					"minLength": 1,
					"maxLength": 128
				}
			},
			"required": [
				"scanId"
			],
			"additionalProperties": false
		}
	},
	{
		"name": "scan_domain",
		"description": "Run a full DNS and email security audit for a single domain. Aggregates every scan-included check in parallel (SPF, DKIM, DMARC, DNSSEC, TLS/SSL, MTA-STS, CAA, BIMI, subdomain takeover, and more) and returns an overall security score, letter grade (A–F), maturity stage, and prioritized findings. Use for a comprehensive single-domain audit, to get a domain's overall security grade, or to assess email security maturity.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"profile": {
					"description": "Scoring profile. Default \"auto\" detects.",
					"type": "string",
					"enum": [
						"auto",
						"mail_enabled",
						"enterprise_mail",
						"non_mail",
						"web_only",
						"minimal",
						"authoritative_dns_infra"
					]
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh scan. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "simulate_attack_paths",
		"description": "Analyze current DNS posture and enumerate specific attack paths an adversary could exploit, with severity, feasibility, steps, and mitigations.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to check (e.g., example.com)"
				},
				"force_refresh": {
					"description": "Bypass cache and run a fresh check. Useful after DNS changes.",
					"type": "boolean"
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain"
			]
		}
	},
	{
		"name": "validate_fix",
		"description": "Re-check a specific security control after applying a fix, to confirm the finding is now resolved. Use only when a fix has already been applied and you want to verify or confirm the remediation was successful — not for initial inspection of a record.",
		"inputSchema": {
			"type": "object",
			"properties": {
				"domain": {
					"type": "string",
					"minLength": 1,
					"maxLength": 253,
					"description": "Domain to validate the fix for"
				},
				"check": {
					"description": "Check name to re-run (e.g., \"dmarc\", \"spf\")",
					"type": "string",
					"enum": [
						"spf",
						"dmarc",
						"dkim",
						"dnssec",
						"ssl",
						"mta_sts",
						"ns",
						"caa",
						"bimi",
						"tlsrpt",
						"http_security",
						"dane"
					]
				},
				"expected": {
					"description": "Expected DNS record value to verify against",
					"type": "string",
					"maxLength": 1000
				},
				"format": {
					"description": "Output verbosity. Auto-detected if omitted.",
					"type": "string",
					"enum": [
						"full",
						"compact"
					]
				}
			},
			"required": [
				"domain",
				"check"
			]
		}
	}
];
